// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtheqKifa2ME7bgBJ189l5gaDKtaFFIWs',
    appId: '1:263063310271:web:e10dab7d1d8efc5a051b0a',
    messagingSenderId: '263063310271',
    projectId: 'websit-cameras',
    authDomain: 'websit-cameras.firebaseapp.com',
    storageBucket: 'websit-cameras.appspot.com',
    measurementId: 'G-DEVBHJ2G6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlnf0d0uarT9uwS_p37rJ5SaNC8r0BQ9Q',
    appId: '1:263063310271:android:83ce01638990f4d3051b0a',
    messagingSenderId: '263063310271',
    projectId: 'websit-cameras',
    storageBucket: 'websit-cameras.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSXRdsbQZ7f6rhJOVPP_gECao_tBIVlg',
    appId: '1:263063310271:ios:87e70eab6c8197b1051b0a',
    messagingSenderId: '263063310271',
    projectId: 'websit-cameras',
    storageBucket: 'websit-cameras.appspot.com',
    iosBundleId: 'com.example.scuritySystemOfffers1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaSXRdsbQZ7f6rhJOVPP_gECao_tBIVlg',
    appId: '1:263063310271:ios:a7be1e4fed84af2e051b0a',
    messagingSenderId: '263063310271',
    projectId: 'websit-cameras',
    storageBucket: 'websit-cameras.appspot.com',
    iosBundleId: 'com.example.scuritySystemOfffers1.RunnerTests',
  );
}
